name: chat_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-182.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  firebase_core: 
  shared_preferences:
  random_string:
  cloud_firestore: 
  google_sign_in:
  google_fonts: ^3.0.1
  cupertino_icons: 
  font_awesome_flutter: ^10.1.0
  animations: ^2.0.3
  intl: ^0.17.0
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0
  dependencies:






flutter:

  
  
  
  uses-material-design: true
  assets:
    - assets/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
